# Generated by Django 5.2.17 on 2026-09-13 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('degree', models.CharField(help_text='ex: SMA, S1 SI', max_length=255)),
                ('description', models.TextField(blank=True, help_text='organisasi/prestasi')),
                ('logo', models.URLField(blank=True, null=True)),
                ('score_label', models.CharField(choices=[('nilai', 'Nilai'), ('ipk', 'IPK')], default='ipk', max_length=10)),
                ('score_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
